// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Data.DbContext;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("turbo_barnacle")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI.Models.ApprovedColumnValues", b =>
                {
                    b.Property<int>("TranslationSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TranslationSeq"));

                    b.Property<int>("ColumnSeq")
                        .HasColumnType("int");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvharcar(2)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TranslationSeq");

                    b.HasIndex("ColumnSeq");

                    b.ToTable("ApprovedColumnValues", "turbo_barnacle");
                });

            modelBuilder.Entity("WebAPI.Models.Column", b =>
                {
                    b.Property<int>("ColumnSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColumnSeq"));

                    b.Property<DateTime>("ColumnCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ColumnFieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("ColumnNeedsApprovedValues")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("ColumnRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ColumnUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("DataTypeSeq")
                        .HasColumnType("int");

                    b.Property<int>("InterfaceSeq")
                        .HasColumnType("int");

                    b.HasKey("ColumnSeq");

                    b.HasIndex("DataTypeSeq");

                    b.HasIndex("InterfaceSeq");

                    b.ToTable("Column", "turbo_barnacle");
                });

            modelBuilder.Entity("WebAPI.Models.ColumnFieldDescription", b =>
                {
                    b.Property<int>("FieldDescriptionSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FieldDescriptionSeq"));

                    b.Property<int>("ColumnSeq")
                        .HasColumnType("int");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FieldDescriptionSeq");

                    b.HasIndex("ColumnSeq");

                    b.ToTable("ColumnFieldDescription", "turbo_barnacle");
                });

            modelBuilder.Entity("WebAPI.Models.Company", b =>
                {
                    b.Property<int>("CompanySeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanySeq"));

                    b.Property<DateTime>("CompanyCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CompanyUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("EntraTenantId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("CompanySeq");

                    b.HasIndex("EntraTenantId")
                        .IsUnique()
                        .HasFilter("[EntraTenantId] IS NOT NULL");

                    b.ToTable("Company", "turbo_barnacle");
                });

            modelBuilder.Entity("WebAPI.Models.Currency", b =>
                {
                    b.Property<int>("CurrencySeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CurrencySeq"));

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CurrencySeq");

                    b.HasIndex("CurrencyCode")
                        .IsUnique();

                    b.ToTable("Currency", "turbo_barnacle");

                    b.HasData(
                        new
                        {
                            CurrencySeq = 1,
                            CurrencyCode = "NOK",
                            CurrencyName = "Norsk krone"
                        },
                        new
                        {
                            CurrencySeq = 2,
                            CurrencyCode = "SEK",
                            CurrencyName = "Svensk krona"
                        },
                        new
                        {
                            CurrencySeq = 3,
                            CurrencyCode = "USD",
                            CurrencyName = "US dollar"
                        },
                        new
                        {
                            CurrencySeq = 4,
                            CurrencyCode = "EUR",
                            CurrencyName = "Euro"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.DataType", b =>
                {
                    b.Property<int>("DataTypeSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DataTypeSeq"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DataTypeSeq");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("DataTypes", "turbo_barnacle");
                });

            modelBuilder.Entity("WebAPI.Models.Interface", b =>
                {
                    b.Property<int>("InterfaceSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterfaceSeq"));

                    b.Property<DateTime>("InterfaceCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("InterfaceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("InterfaceUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("InterfaceSeq");

                    b.ToTable("Interface", "turbo_barnacle");
                });

            modelBuilder.Entity("WebAPI.Models.InterfaceRule", b =>
                {
                    b.Property<int>("RuleSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleSeq"));

                    b.Property<int>("InterfaceSeq")
                        .HasColumnType("int");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RuleTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RuleSeq");

                    b.HasIndex("InterfaceSeq");

                    b.ToTable("InterfaceRule", "turbo_barnacle");
                });

            modelBuilder.Entity("WebAPI.Models.MappingTemplate", b =>
                {
                    b.Property<int>("TemplateSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateSeq"));

                    b.Property<int>("CompanySeq")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserSeq")
                        .HasColumnType("int");

                    b.Property<int>("InterfaceSeq")
                        .HasColumnType("int");

                    b.Property<DateTime>("TemplateCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TemplateSeq");

                    b.HasIndex("CompanySeq");

                    b.HasIndex("CreatedByUserSeq");

                    b.HasIndex("InterfaceSeq");

                    b.ToTable("MappingTemplate", "turbo_barnacle");
                });

            modelBuilder.Entity("WebAPI.Models.MappingTemplateColumn", b =>
                {
                    b.Property<int>("TemplateColumnSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateColumnSeq"));

                    b.Property<string>("OriginalColumn")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TargetColumnSeq")
                        .HasColumnType("int");

                    b.Property<int>("TemplateSeq")
                        .HasColumnType("int");

                    b.HasKey("TemplateColumnSeq");

                    b.HasIndex("TargetColumnSeq");

                    b.HasIndex("TemplateSeq");

                    b.ToTable("MappingTemplateColumn", "turbo_barnacle");
                });

            modelBuilder.Entity("WebAPI.Models.RuleCombination", b =>
                {
                    b.Property<int>("CombinationSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CombinationSeq"));

                    b.Property<int>("RuleSeq")
                        .HasColumnType("int");

                    b.HasKey("CombinationSeq");

                    b.HasIndex("RuleSeq");

                    b.ToTable("RuleCombination", "turbo_barnacle");
                });

            modelBuilder.Entity("WebAPI.Models.RuleCombinationMember", b =>
                {
                    b.Property<int>("MemberSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberSeq"));

                    b.Property<int>("ColumnSeq")
                        .HasColumnType("int");

                    b.Property<int>("CombinationSeq")
                        .HasColumnType("int");

                    b.HasKey("MemberSeq");

                    b.HasIndex("ColumnSeq");

                    b.HasIndex("CombinationSeq");

                    b.ToTable("RuleCombinationMember", "turbo_barnacle");
                });

            modelBuilder.Entity("WebAPI.Models.Status", b =>
                {
                    b.Property<int>("StatusSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusSeq"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusSeq");

                    b.HasIndex("StatusName")
                        .IsUnique();

                    b.ToTable("Status", "turbo_barnacle");
                });

            modelBuilder.Entity("WebAPI.Models.UploadedFile", b =>
                {
                    b.Property<int>("FileSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileSeq"));

                    b.Property<int>("CompanySeq")
                        .HasColumnType("int");

                    b.Property<float>("FileSize")
                        .HasColumnType("real");

                    b.Property<string>("FileStorageHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FileUploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("InterfaceSeq")
                        .HasColumnType("int");

                    b.Property<bool>("IsMapped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("LocalStorage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("StatusSeq")
                        .HasColumnType("int");

                    b.Property<int>("UploadedByUserSeq")
                        .HasColumnType("int");

                    b.HasKey("FileSeq");

                    b.HasIndex("CompanySeq");

                    b.HasIndex("InterfaceSeq");

                    b.HasIndex("StatusSeq");

                    b.HasIndex("UploadedByUserSeq");

                    b.ToTable("UploadedFile", "turbo_barnacle");
                });

            modelBuilder.Entity("WebAPI.Models.User", b =>
                {
                    b.Property<int>("UserSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserSeq"));

                    b.Property<int>("CompanySeq")
                        .HasColumnType("int");

                    b.Property<string>("EntraIdObjectId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UserCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UserUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("UserSeq");

                    b.HasIndex("CompanySeq");

                    b.HasIndex("EntraIdObjectId")
                        .IsUnique()
                        .HasFilter("[EntraIdObjectId] IS NOT NULL");

                    b.HasIndex("UserEmail")
                        .IsUnique();

                    b.ToTable("User", "turbo_barnacle");
                });

            modelBuilder.Entity("WebAPI.Models.ApprovedColumnValues", b =>
                {
                    b.HasOne("WebAPI.Models.Column", "Column")
                        .WithMany()
                        .HasForeignKey("ColumnSeq")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Column");
                });

            modelBuilder.Entity("WebAPI.Models.Column", b =>
                {
                    b.HasOne("WebAPI.Models.DataType", "DataType")
                        .WithMany("Columns")
                        .HasForeignKey("DataTypeSeq")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.Interface", "Interface")
                        .WithMany("Columns")
                        .HasForeignKey("InterfaceSeq")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataType");

                    b.Navigation("Interface");
                });

            modelBuilder.Entity("WebAPI.Models.ColumnFieldDescription", b =>
                {
                    b.HasOne("WebAPI.Models.Column", "Column")
                        .WithMany("ColumnFieldDescriptions")
                        .HasForeignKey("ColumnSeq")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Column");
                });

            modelBuilder.Entity("WebAPI.Models.InterfaceRule", b =>
                {
                    b.HasOne("WebAPI.Models.Interface", "Interface")
                        .WithMany()
                        .HasForeignKey("InterfaceSeq")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Interface");
                });

            modelBuilder.Entity("WebAPI.Models.MappingTemplate", b =>
                {
                    b.HasOne("WebAPI.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanySeq")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserSeq")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.Interface", "Interface")
                        .WithMany()
                        .HasForeignKey("InterfaceSeq")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Interface");
                });

            modelBuilder.Entity("WebAPI.Models.MappingTemplateColumn", b =>
                {
                    b.HasOne("WebAPI.Models.Column", "TargetColumn")
                        .WithMany()
                        .HasForeignKey("TargetColumnSeq")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.MappingTemplate", "Template")
                        .WithMany("ColumnMapping")
                        .HasForeignKey("TemplateSeq")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetColumn");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("WebAPI.Models.RuleCombination", b =>
                {
                    b.HasOne("WebAPI.Models.InterfaceRule", "InterfaceRule")
                        .WithMany("RuleCombinations")
                        .HasForeignKey("RuleSeq")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InterfaceRule");
                });

            modelBuilder.Entity("WebAPI.Models.RuleCombinationMember", b =>
                {
                    b.HasOne("WebAPI.Models.Column", "Column")
                        .WithMany()
                        .HasForeignKey("ColumnSeq")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.RuleCombination", "RuleCombination")
                        .WithMany("RuleCombinationMembers")
                        .HasForeignKey("CombinationSeq")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Column");

                    b.Navigation("RuleCombination");
                });

            modelBuilder.Entity("WebAPI.Models.UploadedFile", b =>
                {
                    b.HasOne("WebAPI.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanySeq")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.Interface", "Interface")
                        .WithMany()
                        .HasForeignKey("InterfaceSeq")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebAPI.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusSeq")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebAPI.Models.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserSeq")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Interface");

                    b.Navigation("Status");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("WebAPI.Models.User", b =>
                {
                    b.HasOne("WebAPI.Models.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanySeq")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("WebAPI.Models.Column", b =>
                {
                    b.Navigation("ColumnFieldDescriptions");
                });

            modelBuilder.Entity("WebAPI.Models.Company", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebAPI.Models.DataType", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("WebAPI.Models.Interface", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("WebAPI.Models.InterfaceRule", b =>
                {
                    b.Navigation("RuleCombinations");
                });

            modelBuilder.Entity("WebAPI.Models.MappingTemplate", b =>
                {
                    b.Navigation("ColumnMapping");
                });

            modelBuilder.Entity("WebAPI.Models.RuleCombination", b =>
                {
                    b.Navigation("RuleCombinationMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
