// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Data.DbContext;

#nullable disable

namespace WebAPI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260327083143_AddUploadedFileStatus")]
    partial class AddUploadedFileStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("turbo_barnacle")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI.Models.Column", b =>
                {
                    b.Property<int>("ColumnSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColumnSeq"));

                    b.Property<DateTime>("ColumnCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ColumnFieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ColumnRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ColumnRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ColumnType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ColumnUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("InterfaceSeq")
                        .HasColumnType("int");

                    b.HasKey("ColumnSeq");

                    b.HasIndex("InterfaceSeq");

                    b.ToTable("Column", "turbo_barnacle");
                });

            modelBuilder.Entity("WebAPI.Models.Company", b =>
                {
                    b.Property<int>("CompanySeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanySeq"));

                    b.Property<DateTime>("CompanyCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CompanyUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("EntraTenantId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("CompanySeq");

                    b.HasIndex("EntraTenantId")
                        .IsUnique()
                        .HasFilter("[EntraTenantId] IS NOT NULL");

                    b.ToTable("Company", "turbo_barnacle");
                });

            modelBuilder.Entity("WebAPI.Models.Interface", b =>
                {
                    b.Property<int>("InterfaceSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterfaceSeq"));

                    b.Property<DateTime>("InterfaceCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("InterfaceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("InterfaceUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("InterfaceSeq");

                    b.ToTable("Interface", "turbo_barnacle");
                });

            modelBuilder.Entity("WebAPI.Models.UploadedFile", b =>
                {
                    b.Property<int>("FileSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileSeq"));

                    b.Property<int>("CompanySeq")
                        .HasColumnType("int");

                    b.Property<float>("FileSize")
                        .HasColumnType("real");

                    b.Property<string>("FileStorageHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FileUploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("InterfaceSeq")
                        .HasColumnType("int");

                    b.Property<bool>("IsMapped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UploadedByUserSeq")
                        .HasColumnType("int");

                    b.HasKey("FileSeq");

                    b.HasIndex("CompanySeq");

                    b.HasIndex("InterfaceSeq");

                    b.HasIndex("UploadedByUserSeq");

                    b.ToTable("UploadedFile", "turbo_barnacle");
                });

            modelBuilder.Entity("WebAPI.Models.User", b =>
                {
                    b.Property<int>("UserSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserSeq"));

                    b.Property<int>("CompanySeq")
                        .HasColumnType("int");

                    b.Property<string>("EntraIdObjectId")
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UserCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UserUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("UserSeq");

                    b.HasIndex("CompanySeq");

                    b.HasIndex("EntraIdObjectId")
                        .IsUnique()
                        .HasFilter("[EntraIdObjectId] IS NOT NULL");

                    b.HasIndex("UserEmail")
                        .IsUnique();

                    b.ToTable("User", "turbo_barnacle");
                });

            modelBuilder.Entity("WebAPI.Models.Column", b =>
                {
                    b.HasOne("WebAPI.Models.Interface", "Interface")
                        .WithMany("Columns")
                        .HasForeignKey("InterfaceSeq")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Interface");
                });

            modelBuilder.Entity("WebAPI.Models.UploadedFile", b =>
                {
                    b.HasOne("WebAPI.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanySeq")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.Interface", "Interface")
                        .WithMany()
                        .HasForeignKey("InterfaceSeq")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebAPI.Models.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserSeq")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Interface");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("WebAPI.Models.User", b =>
                {
                    b.HasOne("WebAPI.Models.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanySeq")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("WebAPI.Models.Company", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebAPI.Models.Interface", b =>
                {
                    b.Navigation("Columns");
                });
#pragma warning restore 612, 618
        }
    }
}
